apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  labels:
   app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-container
        image: lugar2020/react-frontend:docker_tag
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
spec:
  type: NodePort
  ports:
    - port: 30000
      targetPort: 30000
      nodePort: 30006
  selector:
    app: frontend-app

